networks:
  app-net:
    driver: overlay
    attachable: true

services:
  booking:
    #build: ./booking-service
    image: zawodev/booking-service:latest
    #container_name: booking
    env_file: ./booking-service/.env
    networks:
      - app-net
    ports:
      - "8000"
    deploy:
      replicas: 3

  availability:
    #build: ./availability-service
    image: zawodev/availability-service:latest
    #container_name: availability
    env_file: ./availability-service/.env
    networks:
      - app-net
    ports:
      - "8001"
    deploy:
      replicas: 2

  payment:
    #build: ./payment-service
    image: zawodev/payment-service:latest
    #container_name: payment
    env_file: ./payment-service/.env
    networks:
      - app-net
    ports:
      - "8002"

  ticketing:
    #build: ./ticketing-service
    image: zawodev/ticketing-service:latest
    #container_name: ticketing
    env_file: ./ticketing-service/.env
    networks:
      - app-net
    ports:
      - "8003"

  notification:
    #build: ./notification-service
    image: zawodev/notification-service:latest
    #container_name: notification
    env_file: ./notification-service/.env
    networks:
      - app-net
    ports:
      - "8004"
